Internationalization/Controllers/LocalizationController.cs
using System;
using Internationalization.Services;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace Internationalization.Controllers
{
    public class LocalizationController : BaseController
    {
        private readonly ICurrencyService _currencyService;

        public LocalizationController(ICurrencyService currencyService)
        {
            _currencyService = currencyService;
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            SetLanguage(culture);
            return LocalRedirect(returnUrl);
        }

        [HttpPost]
        public IActionResult SetCurrency(string culture, string returnUrl)
        {
            SetCurrency(culture);
            return LocalRedirect(returnUrl);
        }

        public IActionResult ToggleLanguage(string returnUrl)
        {
            var feature = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            // Culture contains the information of the requested culture
            var currentCulture = feature.RequestCulture.Culture;
            var culture = currentCulture.Name == "en-US" ? "zh-CN" : "en-US";
            SetLanguage(culture);
            return LocalRedirect(returnUrl);
        }

        public IActionResult ToggleCurrency(string returnUrl)
        {
            var current = _currencyService.GetCurrent();
            var culture = current.Name == "en-US" ? "zh-CN" : "en-US";
            SetCurrency(culture);
            return LocalRedirect(returnUrl);
        }

    }
}

Internationalization/Views/Shared/_CurrencyTogglePartial.cshtml
@using System.Threading.Tasks
@using Internationalization.Services
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Mvc.Rendering

@inject ICurrencyService CurrencyService

@{
    var culture = CurrencyService.GetCurrent();
}
<!--<div class="pull-right">-->
    <a asp-controller="Localization" asp-action="ToggleCurrency" asp-route-returnUrl="@Context.Request.Path">
        Currency: (@CurrencyService.GetSymbol(culture))
    </a>
<!--</div>-->

Internationalization/Views/Shared/_LanguageTogglePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Mvc.Rendering

@{
    var culture = Context.Features.Get<IRequestCultureFeature>();
}
<!--<div class="pull-right">-->
    <a asp-controller="Localization" asp-action="ToggleLanguage" asp-route-returnUrl="@Context.Request.Path">
        Switch language (@culture.RequestCulture.UICulture.Name)
    </a>
<!--</div>-->

Internationalization/Views/Shared/_Layout.cshtml
@using System.Globalization
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Internationalization</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Internationalization</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
                <ul class="nav navbar-nav navbar-right">
                    @await Html.PartialAsync("_SelectCurrencyPartial")
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@await Html.PartialAsync("_CurrencyTogglePartial")</p>
            <p>@await Html.PartialAsync("_LanguageTogglePartial")</p>
            <p>&copy; 2017 - Internationalization</p>
        </footer>
    </div>
    
    <script>
        window.globalSetting = {};
        window.globalSetting.lang = '@CultureInfo.CurrentCulture.Name';
    </script>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @if (CultureInfo.CurrentCulture.Name == "zh-CN")
        {
            // Chinese scripts
        }
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script language="javascript">
            /*global jQuery, window*/

        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Internationalization/Views/Shared/_SelectCurrencyPartial.cshtml
@using System.Collections.Generic
@using System.Linq
@using System.Threading.Tasks
@using Internationalization.Services
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Mvc.Rendering

@inject IViewLocalizer Localizer
@inject ICurrencyService CurrencyService

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var current = CurrencyService.GetCurrent();
    var availableCurrencies = CurrencyService
        .GetAll()
        .Select(c => new SelectListItem
        {
            Value = c.CultureName,
            Text = c.Symbol
        });
}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Currency (@CurrencyService.GetISOName(current))
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu currency-selector">
        @foreach (var currency in availableCurrencies)
        {
            if (currency.Text == CurrencyService.GetISOName(current))
            {
                <li><a href="#" data-value="@currency.Value">@currency.Text <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></li>
            }
            else
            {
                <li><a href="#" data-value="@currency.Value">@currency.Text</a></li>
            }
        }
    </ul>
    <form asp-controller="Localization" asp-action="SetCurrency" asp-route-returnUrl="@Context.Request.Path"
                method="post" id="currency-form" role="form">
        <input type="hidden" name="culture" value="@current" />
    </form>
</li>

Internationalization/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Collections.Generic
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Mvc.Rendering

@inject IViewLocalizer Localizer

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var availableCultures = new List<SelectListItem>
    {
        new SelectListItem
        {
            Value = "en-US",
            Text = "English"
        },
        new SelectListItem
        {
            Value = "zh-CN",
            Text = "Chinese"
        }
    };
}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Language (@requestCulture.RequestCulture.UICulture.Name)
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu lang-selector">
        @foreach (var lang in availableCultures)
        {
            if (lang.Value == requestCulture.RequestCulture.UICulture.Name)
            {
                <li><a href="#" data-value="@lang.Value">@lang.Text <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></li>
            }
            else
            {
                <li><a href="#" data-value="@lang.Value">@lang.Text</a></li>
            }
        }
    </ul>
    <form asp-controller="Localization" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
                method="post" id="lang-form" role="form">
        <input type="hidden" name="culture" value="@requestCulture.RequestCulture.UICulture.Name" />
    </form>
</li>